version: '3.3'

services:
  redis:
    image: redis:alpine3.11
    container_name: redis-server
    ports: 
      - 6379:6379
    expose:
      - 6379

  redis-publisher:
    build:
      context: .
      dockerfile: redis_python.Dockerfile
    image: redis_py3:latest
    container_name: redis-publisher
    entrypoint: ["python", "redis_pub.py"]

