version: "3.4"

services:
  redis:
    image: redis:alpine3.11
    container_name: redis-server
    ports: 
      - 6379:6379
    expose:
      - 6379

  redis-publisher:
    build:
      context: .
      dockerfile: redis_publisher.Dockerfile
    image: redis_pub:latest
    container_name: redis-publisher
    depends_on:
        - redis
    entrypoint: ["python", "redis_pub.py"]
    healthcheck:
      test: ["CMD", "python", "/check_pub.py"]
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 5s

  redis-subscriber:
    build:
      context: .
      dockerfile: redis_subscriber.Dockerfile
    image: redis_sub:latest
    container_name: redis-subscriber
    depends_on:
        - redis
    entrypoint: ["python", "redis_sub.py"]

